#!/usr/bin/env python3
"""
docs/tts-script.md (파트별 실제 TTS 원문)과 public/audio/timeline.json
(각 wav의 실측 길이)을 합쳐서, 화면에 12자 안팎으로 나오는 자막 청크
타임라인을 생성한다. 결과는 src/data/subtitles.generated.ts,
src/data/audioParts.generated.ts 로 저장.
"""
import json
import re
import os

FPS = 30
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT_MD = os.path.join(ROOT, "docs/tts-script.md")
TIMELINE_JSON = os.path.join(ROOT, "public/audio/timeline.json")
OUT_SUBS = os.path.join(ROOT, "src/data/subtitles.generated.ts")
OUT_AUDIO = os.path.join(ROOT, "src/data/audioParts.generated.ts")

TARGET_LEN = 12
MAX_LEN = 16

def parse_parts(md: str):
    # split on "## 파트 NN" headers
    blocks = re.split(r"\n## 파트 (\d+)\s.*\n", md)
    # blocks[0] is preamble; then alternating (partNum, body)
    parts = {}
    it = iter(blocks[1:])
    for num, body in zip(it, it):
        # drop the "*원고 구간: ...*" line
        body = re.sub(r"^\*원고 구간:.*\*\n", "", body.strip(), flags=re.MULTILINE)
        body = body.strip()
        # stop at the next "---" separator
        body = body.split("\n---")[0].strip()
        paragraphs = [p.strip() for p in re.split(r"\n\s*\n", body) if p.strip()]
        parts[int(num)] = paragraphs
    return parts

def chunk_paragraph(text: str):
    words = text.split(" ")
    chunks = []
    cur = ""
    for w in words:
        candidate = (cur + " " + w).strip() if cur else w
        if not cur:
            cur = w
            continue
        if len(candidate) <= TARGET_LEN:
            cur = candidate
        elif len(cur) < 6 and len(candidate) <= MAX_LEN:
            # too short a chunk on its own -- allow slight overflow
            cur = candidate
        else:
            chunks.append(cur)
            cur = w
    if cur:
        chunks.append(cur)
    return chunks

def main():
    with open(SCRIPT_MD, encoding="utf-8") as f:
        md = f.read()
    with open(TIMELINE_JSON, encoding="utf-8") as f:
        timeline = json.load(f)

    parts_text = parse_parts(md)
    seg_by_num = {}
    for seg in timeline["segments"]:
        # 6-1.wav is an inserted correction clip, not part of the 25 main parts
        name = seg["file"]
        if name == "6-1.wav":
            continue
        num = int(name.replace(".wav", ""))
        seg_by_num[num] = seg

    assert set(parts_text.keys()) == set(seg_by_num.keys()), (
        set(parts_text.keys()) ^ set(seg_by_num.keys())
    )

    subtitle_lines = []
    audio_parts = []

    for num in sorted(parts_text.keys()):
        paragraphs = parts_text[num]
        seg = seg_by_num[num]
        part_start = seg["startSec"]
        part_dur = seg["durationSec"]

        audio_parts.append({
            "part": num,
            "file": seg["file"],
            "startSec": part_start,
            "durationSec": part_dur,
        })

        total_chars = sum(len(p) for p in paragraphs)
        cursor = part_start
        for p in paragraphs:
            p_dur = part_dur * (len(p) / total_chars) if total_chars else 0
            p_start = cursor
            chunks = chunk_paragraph(p)
            chunk_total_chars = sum(len(c) for c in chunks)
            sub_cursor = p_start
            for c in chunks:
                c_dur = p_dur * (len(c) / chunk_total_chars) if chunk_total_chars else 0
                start = sub_cursor
                end = sub_cursor + c_dur
                subtitle_lines.append({
                    "text": c,
                    "startFrame": round(start * FPS),
                    "endFrame": round(end * FPS),
                    "part": num,
                })
                sub_cursor = end
            cursor = p_start + p_dur

    # ensure no zero-length / overlapping frames from rounding
    for i in range(1, len(subtitle_lines)):
        if subtitle_lines[i]["startFrame"] < subtitle_lines[i - 1]["endFrame"]:
            subtitle_lines[i]["startFrame"] = subtitle_lines[i - 1]["endFrame"]
        if subtitle_lines[i]["endFrame"] <= subtitle_lines[i]["startFrame"]:
            subtitle_lines[i]["endFrame"] = subtitle_lines[i]["startFrame"] + 1

    os.makedirs(os.path.dirname(OUT_SUBS), exist_ok=True)

    with open(OUT_SUBS, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/gen-subtitles.py — do not hand-edit.\n")
        f.write("import {SubtitleLine} from '../components/Subtitle';\n\n")
        f.write("export const fullSubtitles: (SubtitleLine & {part: number})[] = ")
        f.write(json.dumps(subtitle_lines, ensure_ascii=False, indent=2))
        f.write(";\n")

    with open(OUT_AUDIO, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/gen-subtitles.py — do not hand-edit.\n\n")
        f.write("export type AudioPart = {part: number; file: string; startSec: number; durationSec: number};\n\n")
        f.write("export const audioParts: AudioPart[] = ")
        f.write(json.dumps(audio_parts, ensure_ascii=False, indent=2))
        f.write(";\n\n")
        total = timeline["totalDurationSec"]
        f.write(f"export const TOTAL_DURATION_SEC = {total};\n")

    print(f"parts: {len(parts_text)}, subtitle chunks: {len(subtitle_lines)}")
    print(f"total duration: {timeline['totalDurationSec']:.1f}s = {timeline['totalDurationSec']/60:.2f} min")

if __name__ == "__main__":
    main()
