// AUTO-GENERATED by scripts/gen-subtitles.py — do not hand-edit.

export type AudioPart = {part: number; file: string; startSec: number; durationSec: number};

export const audioParts: AudioPart[] = [
  {
    "part": 1,
    "file": "1.wav",
    "startSec": 0.0,
    "durationSec": 52.16
  },
  {
    "part": 2,
    "file": "2.wav",
    "startSec": 52.16,
    "durationSec": 42.76
  },
  {
    "part": 3,
    "file": "3.wav",
    "startSec": 94.92,
    "durationSec": 41.92
  },
  {
    "part": 4,
    "file": "4.wav",
    "startSec": 136.84,
    "durationSec": 48.8
  },
  {
    "part": 5,
    "file": "5.wav",
    "startSec": 185.64,
    "durationSec": 45.32
  },
  {
    "part": 6,
    "file": "6.wav",
    "startSec": 230.96,
    "durationSec": 47.76
  },
  {
    "part": 6.1,
    "file": "6-1.wav",
    "startSec": 278.72,
    "durationSec": 3.56
  },
  {
    "part": 7,
    "file": "7.wav",
    "startSec": 282.28,
    "durationSec": 47.48
  },
  {
    "part": 8,
    "file": "8.wav",
    "startSec": 329.76,
    "durationSec": 41.24
  },
  {
    "part": 9,
    "file": "9.wav",
    "startSec": 371.0,
    "durationSec": 41.2
  },
  {
    "part": 10,
    "file": "10.wav",
    "startSec": 412.2,
    "durationSec": 42.88
  },
  {
    "part": 11,
    "file": "11.wav",
    "startSec": 455.08,
    "durationSec": 41.0
  },
  {
    "part": 12,
    "file": "12.wav",
    "startSec": 496.08,
    "durationSec": 46.96
  },
  {
    "part": 13,
    "file": "13.wav",
    "startSec": 543.04,
    "durationSec": 43.32
  },
  {
    "part": 14,
    "file": "14.wav",
    "startSec": 586.36,
    "durationSec": 46.84
  },
  {
    "part": 15,
    "file": "15.wav",
    "startSec": 633.2,
    "durationSec": 41.2
  },
  {
    "part": 16,
    "file": "16.wav",
    "startSec": 674.4,
    "durationSec": 48.72
  },
  {
    "part": 17,
    "file": "17.wav",
    "startSec": 723.12,
    "durationSec": 51.72
  },
  {
    "part": 18,
    "file": "18.wav",
    "startSec": 774.84,
    "durationSec": 39.24
  },
  {
    "part": 19,
    "file": "19.wav",
    "startSec": 814.08,
    "durationSec": 37.56
  },
  {
    "part": 20,
    "file": "20.wav",
    "startSec": 851.64,
    "durationSec": 48.6
  },
  {
    "part": 21,
    "file": "21.wav",
    "startSec": 900.24,
    "durationSec": 56.6
  },
  {
    "part": 22,
    "file": "22.wav",
    "startSec": 956.84,
    "durationSec": 49.92
  },
  {
    "part": 23,
    "file": "23.wav",
    "startSec": 1006.76,
    "durationSec": 39.4
  },
  {
    "part": 24,
    "file": "24.wav",
    "startSec": 1046.16,
    "durationSec": 46.72
  },
  {
    "part": 25,
    "file": "25.wav",
    "startSec": 1092.88,
    "durationSec": 52.24
  }
];

export const TOTAL_DURATION_SEC = 1145.12;
