// AUTO-GENERATED by scripts/gen-subtitles.py — do not hand-edit.
import {SubtitleLine} from '../components/Subtitle';

export const fullSubtitles: (SubtitleLine & {part: number})[] = [
  {
    "text": "오늘 우리가 추적할 이 코인은, 가격이 흔들리면 안 됩니다.",
    "startFrame": 0,
    "endFrame": 133,
    "part": 1
  },
  {
    "text": "무슨 일이 있어도 1달러.",
    "startFrame": 133,
    "endFrame": 189,
    "part": 1
  },
  {
    "text": "그러라고 만든 코인이거든요.",
    "startFrame": 189,
    "endFrame": 249,
    "part": 1
  },
  {
    "text": "그런데 흔들립니다.",
    "startFrame": 249,
    "endFrame": 288,
    "part": 1
  },
  {
    "text": "그리고 무너집니다.",
    "startFrame": 288,
    "endFrame": 327,
    "part": 1
  },
  {
    "text": "이 코인을 떠받치던 짝꿍 코인도 같이 무너집니다.",
    "startFrame": 327,
    "endFrame": 436,
    "part": 1
  },
  {
    "text": "한 달 전에 119달러였습니다.",
    "startFrame": 436,
    "endFrame": 504,
    "part": 1
  },
  {
    "text": "지금은 휴지조각이고요.",
    "startFrame": 504,
    "endFrame": 553,
    "part": 1
  },
  {
    "text": "그사이 이 코인은 10억 개에서 6조 개로 불어납니다.",
    "startFrame": 553,
    "endFrame": 675,
    "part": 1
  },
  {
    "text": "6천 배요.",
    "startFrame": 675,
    "endFrame": 699,
    "part": 1
  },
  {
    "text": "오타 아닙니다.",
    "startFrame": 699,
    "endFrame": 732,
    "part": 1
  },
  {
    "text": "미국 증권거래위원회는 이 사태로 하룻밤 사이에 약 400억 달러가 증발했다고 밝혔습니다.",
    "startFrame": 732,
    "endFrame": 926,
    "part": 1
  },
  {
    "text": "우리 돈 50조 원.",
    "startFrame": 926,
    "endFrame": 969,
    "part": 1
  },
  {
    "text": "여기까지 걸린 시간, 사흘입니다.",
    "startFrame": 969,
    "endFrame": 1039,
    "part": 1
  },
  {
    "text": "그런데 이 사건, 정말 이상한 구석이 하나 있습니다.",
    "startFrame": 1039,
    "endFrame": 1152,
    "part": 1
  },
  {
    "text": "도둑이 없어요.",
    "startFrame": 1152,
    "endFrame": 1184,
    "part": 1
  },
  {
    "text": "누가 금고를 턴 것도, 서버를 해킹한 것도 아닙니다.",
    "startFrame": 1184,
    "endFrame": 1301,
    "part": 1
  },
  {
    "text": "시스템은 설계도대로, 아주 성실하게 작동했습니다.",
    "startFrame": 1301,
    "endFrame": 1409,
    "part": 1
  },
  {
    "text": "설계도대로 작동했는데 50조가 사라졌습니다.",
    "startFrame": 1409,
    "endFrame": 1503,
    "part": 1
  },
  {
    "text": "어떻게 이런 일이 가능할까요.",
    "startFrame": 1503,
    "endFrame": 1565,
    "part": 1
  },
  {
    "text": "그걸 알려면 사흘 전으로 돌아가야 합니다.",
    "startFrame": 1565,
    "endFrame": 1652,
    "part": 2
  },
  {
    "text": "아니, 조금 더 앞으로.",
    "startFrame": 1652,
    "endFrame": 1701,
    "part": 2
  },
  {
    "text": "사람들이 이 코인에 돈을 넣기 시작한 그때까지요.",
    "startFrame": 1701,
    "endFrame": 1804,
    "part": 2
  },
  {
    "text": "돈이 움직인 사건을 추적합니다.",
    "startFrame": 1804,
    "endFrame": 1868,
    "part": 2
  },
  {
    "text": "돈의 궤적, 1화 시작합니다.",
    "startFrame": 1868,
    "endFrame": 1929,
    "part": 2
  },
  {
    "text": "자, 사흘 전으로 돌아왔습니다.",
    "startFrame": 1929,
    "endFrame": 1992,
    "part": 2
  },
  {
    "text": "이때만 해도 이 코인은 세상에서 제일 지루한 코인이었습니다.",
    "startFrame": 1992,
    "endFrame": 2116,
    "part": 2
  },
  {
    "text": "보세요.",
    "startFrame": 2116,
    "endFrame": 2132,
    "part": 2
  },
  {
    "text": "아무 일도 안 일어나죠.",
    "startFrame": 2132,
    "endFrame": 2183,
    "part": 2
  },
  {
    "text": "이게 정상입니다.",
    "startFrame": 2183,
    "endFrame": 2218,
    "part": 2
  },
  {
    "text": "아니, 이게 이 코인의 존재 이유였어요.",
    "startFrame": 2218,
    "endFrame": 2304,
    "part": 2
  },
  {
    "text": "스테이블코인이라고 합니다.",
    "startFrame": 2304,
    "endFrame": 2357,
    "part": 2
  },
  {
    "text": "우리말로 하면 안정 코인 정도.",
    "startFrame": 2357,
    "endFrame": 2422,
    "part": 2
  },
  {
    "text": "비트코인처럼 하루에 10%씩 널뛰는 게 아니라,",
    "startFrame": 2422,
    "endFrame": 2521,
    "part": 2
  },
  {
    "text": "계속 1달러에 딱 붙어 있는 코인이에요.",
    "startFrame": 2521,
    "endFrame": 2605,
    "part": 2
  },
  {
    "text": "백화점 상품권 생각하시면 됩니다.",
    "startFrame": 2605,
    "endFrame": 2673,
    "part": 2
  },
  {
    "text": "1만 원짜리 상품권이 왜 1만 원 값을 하죠?",
    "startFrame": 2673,
    "endFrame": 2768,
    "part": 2
  },
  {
    "text": "백화점 창고에 진짜 물건이 있으니까요.",
    "startFrame": 2768,
    "endFrame": 2848,
    "part": 2
  },
  {
    "text": "대부분의 스테이블코인이 이 방식입니다.",
    "startFrame": 2848,
    "endFrame": 2925,
    "part": 3
  },
  {
    "text": "코인을 하나 찍을 때마다 진짜 달러나 미국 국채를 금고에 넣어둡니다.",
    "startFrame": 2925,
    "endFrame": 3066,
    "part": 3
  },
  {
    "text": "의심되면 언제든 와서 바꿔가라.",
    "startFrame": 3066,
    "endFrame": 3129,
    "part": 3
  },
  {
    "text": "담보가 있다는 건 이런 겁니다.",
    "startFrame": 3129,
    "endFrame": 3193,
    "part": 3
  },
  {
    "text": "그런데 UST한테는 이 금고가 없었습니다.",
    "startFrame": 3193,
    "endFrame": 3275,
    "part": 3
  },
  {
    "text": "대신 코드를 넣었어요.",
    "startFrame": 3275,
    "endFrame": 3319,
    "part": 3
  },
  {
    "text": "가격이 1달러에서 벗어나면 자동으로 되돌리는 장치를 짜 넣은 겁니다.",
    "startFrame": 3319,
    "endFrame": 3459,
    "part": 3
  },
  {
    "text": "그래서 이런 코인을 알고리즘 스테이블코인이라고 부릅니다.",
    "startFrame": 3459,
    "endFrame": 3573,
    "part": 3
  },
  {
    "text": "그 장치의 파트너가 루나입니다.",
    "startFrame": 3573,
    "endFrame": 3636,
    "part": 3
  },
  {
    "text": "아까 오프닝에서 절벽처럼 떨어지던 그 코인이요.",
    "startFrame": 3636,
    "endFrame": 3732,
    "part": 3
  },
  {
    "text": "UST의 짝꿍이자, 사실상 유일한 안전장치였습니다.",
    "startFrame": 3732,
    "endFrame": 3836,
    "part": 3
  },
  {
    "text": "원리는 어렵지 않아요.",
    "startFrame": 3836,
    "endFrame": 3880,
    "part": 3
  },
  {
    "text": "자판기 하나만 떠올려 주세요.",
    "startFrame": 3880,
    "endFrame": 3940,
    "part": 3
  },
  {
    "text": "테라 시스템 한가운데 자판기가 한 대 있다고 칩시다.",
    "startFrame": 3940,
    "endFrame": 4046,
    "part": 3
  },
  {
    "text": "하는 일은 딱 두 가지입니다.",
    "startFrame": 4046,
    "endFrame": 4105,
    "part": 3
  },
  {
    "text": "UST를 넣으면 1달러어치 루나가 나옵니다.",
    "startFrame": 4105,
    "endFrame": 4198,
    "part": 4
  },
  {
    "text": "루나를 넣으면 그만큼의 UST가 나오고요.",
    "startFrame": 4198,
    "endFrame": 4287,
    "part": 4
  },
  {
    "text": "누가 오든, 가격이 얼마든, 이 교환은 무조건 됩니다.",
    "startFrame": 4287,
    "endFrame": 4403,
    "part": 4
  },
  {
    "text": "금고에 달러는 없다.",
    "startFrame": 4403,
    "endFrame": 4446,
    "part": 4
  },
  {
    "text": "대신 이 자판기는 절대 안 멈춘다.",
    "startFrame": 4446,
    "endFrame": 4521,
    "part": 4
  },
  {
    "text": "UST가 내건 약속은 이게 전부였습니다.",
    "startFrame": 4521,
    "endFrame": 4608,
    "part": 4
  },
  {
    "text": "이게 다예요.",
    "startFrame": 4608,
    "endFrame": 4636,
    "part": 4
  },
  {
    "text": "앞으로 \"태운다\"는 말이 계속 나옵니다.",
    "startFrame": 4636,
    "endFrame": 4722,
    "part": 4
  },
  {
    "text": "소각이라고도 하는데요.",
    "startFrame": 4722,
    "endFrame": 4769,
    "part": 4
  },
  {
    "text": "이거 하나만 잘못 이해하면 뒤가 통째로 꼬입니다.",
    "startFrame": 4769,
    "endFrame": 4875,
    "part": 4
  },
  {
    "text": "잠깐만 짚고 갈게요.",
    "startFrame": 4875,
    "endFrame": 4918,
    "part": 4
  },
  {
    "text": "판다는 건 내 코인이 다른 사람 손으로 넘어가는 겁니다.",
    "startFrame": 4918,
    "endFrame": 5039,
    "part": 4
  },
  {
    "text": "주인만 바뀌죠.",
    "startFrame": 5039,
    "endFrame": 5070,
    "part": 4
  },
  {
    "text": "세상에 있는 코인 개수는 그대로입니다.",
    "startFrame": 5070,
    "endFrame": 5151,
    "part": 4
  },
  {
    "text": "태운다는 건 그 코인이 아예 없어지는 겁니다.",
    "startFrame": 5151,
    "endFrame": 5247,
    "part": 4
  },
  {
    "text": "아무도 열 수 없는 주소로 보내버려서 총 개수를 줄여버리는 거예요.",
    "startFrame": 5247,
    "endFrame": 5389,
    "part": 4
  },
  {
    "text": "한국은행이 헌 돈 파쇄하는 장면 보신 적 있죠.",
    "startFrame": 5389,
    "endFrame": 5491,
    "part": 4
  },
  {
    "text": "그겁니다.",
    "startFrame": 5491,
    "endFrame": 5510,
    "part": 4
  },
  {
    "text": "파는 게 아니라 없애는 것.",
    "startFrame": 5510,
    "endFrame": 5569,
    "part": 4
  },
  {
    "text": "그러니까 아까 그 자판기는 사실 이렇게 생긴 물건입니다.",
    "startFrame": 5569,
    "endFrame": 5687,
    "part": 5
  },
  {
    "text": "한쪽은 파쇄기, 한쪽은 인쇄기.",
    "startFrame": 5687,
    "endFrame": 5751,
    "part": 5
  },
  {
    "text": "루나를 넣으면 그 루나는 태워지고,",
    "startFrame": 5751,
    "endFrame": 5825,
    "part": 5
  },
  {
    "text": "UST가 새로 찍혀 나옵니다.",
    "startFrame": 5825,
    "endFrame": 5887,
    "part": 5
  },
  {
    "text": "UST를 넣으면 그 UST가 태워지고,",
    "startFrame": 5887,
    "endFrame": 5968,
    "part": 5
  },
  {
    "text": "루나가 새로 찍혀 나오고요.",
    "startFrame": 5968,
    "endFrame": 6026,
    "part": 5
  },
  {
    "text": "한쪽이 줄면 다른 쪽이 늘어납니다.",
    "startFrame": 6026,
    "endFrame": 6099,
    "part": 5
  },
  {
    "text": "시소처럼요.",
    "startFrame": 6099,
    "endFrame": 6122,
    "part": 5
  },
  {
    "text": "이거 하나만 붙잡고 계시면 오늘 이야기는 끝까지 다 따라오실 수 있습니다.",
    "startFrame": 6122,
    "endFrame": 6279,
    "part": 5
  },
  {
    "text": "UST가 0.98달러로 싸졌다고 해보죠.",
    "startFrame": 6279,
    "endFrame": 6360,
    "part": 5
  },
  {
    "text": "여기서 눈치 빠른 사람이 등장합니다.",
    "startFrame": 6360,
    "endFrame": 6438,
    "part": 5
  },
  {
    "text": "시장에서 0.98달러에 UST를 삽니다.",
    "startFrame": 6438,
    "endFrame": 6523,
    "part": 5
  },
  {
    "text": "자판기에 넣습니다.",
    "startFrame": 6523,
    "endFrame": 6562,
    "part": 5
  },
  {
    "text": "자판기는 규칙대로 1달러어치 루나를 뱉어줍니다.",
    "startFrame": 6562,
    "endFrame": 6663,
    "part": 5
  },
  {
    "text": "그걸 팔면 2센트가 남죠.",
    "startFrame": 6663,
    "endFrame": 6717,
    "part": 5
  },
  {
    "text": "이 사람 입장에선 그냥 용돈벌이입니다.",
    "startFrame": 6717,
    "endFrame": 6796,
    "part": 5
  },
  {
    "text": "그런데 결과적으로 시장에 있던 UST를 태워 없앤 셈이 됩니다.",
    "startFrame": 6796,
    "endFrame": 6929,
    "part": 5
  },
  {
    "text": "물건이 흔하면 값이 떨어지고, 귀해지면 값이 오르잖아요.",
    "startFrame": 6929,
    "endFrame": 7050,
    "part": 6
  },
  {
    "text": "시장에 UST가 줄어드니까 값이 올라가는 겁니다.",
    "startFrame": 7050,
    "endFrame": 7156,
    "part": 6
  },
  {
    "text": "0.98에서 다시 1달러로요.",
    "startFrame": 7156,
    "endFrame": 7219,
    "part": 6
  },
  {
    "text": "반대 상황도 똑같습니다.",
    "startFrame": 7219,
    "endFrame": 7271,
    "part": 6
  },
  {
    "text": "UST가 1.02달러로 비싸지면 이번엔 루나를 자판기에 넣습니다.",
    "startFrame": 7271,
    "endFrame": 7415,
    "part": 6
  },
  {
    "text": "루나가 태워지고 UST가 나오죠.",
    "startFrame": 7415,
    "endFrame": 7487,
    "part": 6
  },
  {
    "text": "그걸 1.02에 팔면 또 2센트.",
    "startFrame": 7487,
    "endFrame": 7559,
    "part": 6
  },
  {
    "text": "이번엔 시장에 UST가 늘어났으니,",
    "startFrame": 7559,
    "endFrame": 7635,
    "part": 6
  },
  {
    "text": "흔해진 만큼 값이 내려옵니다.",
    "startFrame": 7635,
    "endFrame": 7699,
    "part": 6
  },
  {
    "text": "다시 1달러로요.",
    "startFrame": 7699,
    "endFrame": 7735,
    "part": 6
  },
  {
    "text": "솔직히 좀 기발하죠?",
    "startFrame": 7735,
    "endFrame": 7779,
    "part": 6
  },
  {
    "text": "누가 지켜보고 있을 필요도 없어요.",
    "startFrame": 7779,
    "endFrame": 7855,
    "part": 6
  },
  {
    "text": "돈 벌고 싶은 사람들이 알아서 가격을 1달러에 붙여주니까요.",
    "startFrame": 7855,
    "endFrame": 7987,
    "part": 6
  },
  {
    "text": "그리고 실제로 잘 굴러갔습니다.",
    "startFrame": 7987,
    "endFrame": 8055,
    "part": 6
  },
  {
    "text": "한동안은요.",
    "startFrame": 8055,
    "endFrame": 8079,
    "part": 6
  },
  {
    "text": "이 구조를 만들고 끌고 간 사람이 권도형이었습니다.",
    "startFrame": 8079,
    "endFrame": 8189,
    "part": 6
  },
  {
    "text": "새로운 금융 시스템을 만들고 있다고 했죠.",
    "startFrame": 8189,
    "endFrame": 8279,
    "part": 6
  },
  {
    "text": "시장도 한동안은 그 자신감을 믿었고요.",
    "startFrame": 8279,
    "endFrame": 8362,
    "part": 6
  },
  {
    "text": "여기까지가 밖에서 보이던 그림입니다.",
    "startFrame": 8468,
    "endFrame": 8542,
    "part": 7
  },
  {
    "text": "근데 장부를 한 줄씩 열어보면, 좀 다른 게 보입니다.",
    "startFrame": 8542,
    "endFrame": 8653,
    "part": 7
  },
  {
    "text": "아까 그 자판기 안내문, 한 번만 더 읽어보겠습니다.",
    "startFrame": 8653,
    "endFrame": 8760,
    "part": 7
  },
  {
    "text": "\"UST 1개 = 1달러어치 루나.\"",
    "startFrame": 8760,
    "endFrame": 8834,
    "part": 7
  },
  {
    "text": "질문 하나 드릴게요.",
    "startFrame": 8834,
    "endFrame": 8874,
    "part": 7
  },
  {
    "text": "그 자판기 안에 달러가 한 장이라도 들어 있을까요?",
    "startFrame": 8874,
    "endFrame": 8978,
    "part": 7
  },
  {
    "text": "한 장도 없습니다.",
    "startFrame": 8978,
    "endFrame": 9016,
    "part": 7
  },
  {
    "text": "자판기가 내주는 건 처음부터 끝까지 루나뿐이었어요.",
    "startFrame": 9016,
    "endFrame": 9121,
    "part": 7
  },
  {
    "text": "루나가 1달러 값을 한다.",
    "startFrame": 9121,
    "endFrame": 9174,
    "part": 7
  },
  {
    "text": "딱 이 전제 하나로 돌아가던 기계였습니다.",
    "startFrame": 9174,
    "endFrame": 9260,
    "part": 7
  },
  {
    "text": "그러니까 이 시스템의 진짜 담보는 달러가 아니라 루나 가격이었습니다.",
    "startFrame": 9260,
    "endFrame": 9401,
    "part": 7
  },
  {
    "text": "그럼 루나 가격은 뭐가 받쳐주고 있었을까요.",
    "startFrame": 9401,
    "endFrame": 9490,
    "part": 7
  },
  {
    "text": "테라가 잘될 거라는 믿음이었습니다.",
    "startFrame": 9490,
    "endFrame": 9560,
    "part": 7
  },
  {
    "text": "UST를 받치는 건 루나, 루나를 받치는 건 믿음.",
    "startFrame": 9560,
    "endFrame": 9663,
    "part": 7
  },
  {
    "text": "믿음이 흔들리면 담보도 같이 흔들리는 구조였던 거죠.",
    "startFrame": 9663,
    "endFrame": 9770,
    "part": 7
  },
  {
    "text": "이 구조가 나중에 어떤 일을 벌이는지, 조금만 기다려 주세요.",
    "startFrame": 9770,
    "endFrame": 9893,
    "part": 7
  },
  {
    "text": "근데 여기서 이상한 게 하나 있습니다.",
    "startFrame": 9893,
    "endFrame": 9978,
    "part": 8
  },
  {
    "text": "사람들이 이 코인을 대체 왜 샀을까요?",
    "startFrame": 9978,
    "endFrame": 10063,
    "part": 8
  },
  {
    "text": "가격이 오르질 않는데요.",
    "startFrame": 10063,
    "endFrame": 10116,
    "part": 8
  },
  {
    "text": "1달러에 사면 영원히 1달러입니다.",
    "startFrame": 10116,
    "endFrame": 10193,
    "part": 8
  },
  {
    "text": "앵커 프로토콜이라는 게 있었습니다.",
    "startFrame": 10193,
    "endFrame": 10270,
    "part": 8
  },
  {
    "text": "이름은 거창한데 정체는 별거 없어요.",
    "startFrame": 10270,
    "endFrame": 10352,
    "part": 8
  },
  {
    "text": "코인 저축 앱입니다.",
    "startFrame": 10352,
    "endFrame": 10396,
    "part": 8
  },
  {
    "text": "은행 앱 쓰시죠.",
    "startFrame": 10396,
    "endFrame": 10433,
    "part": 8
  },
  {
    "text": "돈 넣어두면 이자 붙는 그거요.",
    "startFrame": 10433,
    "endFrame": 10503,
    "part": 8
  },
  {
    "text": "앵커는 그걸 코인으로 합니다.",
    "startFrame": 10503,
    "endFrame": 10568,
    "part": 8
  },
  {
    "text": "UST를 넣어두면 이자가 붙어요.",
    "startFrame": 10568,
    "endFrame": 10642,
    "part": 8
  },
  {
    "text": "다른 점이라면 은행은 직원과 지점이 굴리는데,",
    "startFrame": 10642,
    "endFrame": 10744,
    "part": 8
  },
  {
    "text": "앵커는 코드가 굴린다는 것 정도.",
    "startFrame": 10744,
    "endFrame": 10818,
    "part": 8
  },
  {
    "text": "그리고 이 앱이 걸어놓은 이자율이 연 19.5%였습니다.",
    "startFrame": 10818,
    "endFrame": 10939,
    "part": 8
  },
  {
    "text": "그때 은행 예금이 잘 받아야 2~3%였습니다.",
    "startFrame": 10939,
    "endFrame": 11040,
    "part": 8
  },
  {
    "text": "여기는 거의 20%예요.",
    "startFrame": 11040,
    "endFrame": 11093,
    "part": 8
  },
  {
    "text": "은행의 일곱 배.",
    "startFrame": 11093,
    "endFrame": 11130,
    "part": 8
  },
  {
    "text": "여기서 하나 짚고 갈 게 있습니다.",
    "startFrame": 11130,
    "endFrame": 11205,
    "part": 9
  },
  {
    "text": "UST를 사기만 해서는 이자가 한 푼도 안 붙습니다.",
    "startFrame": 11205,
    "endFrame": 11320,
    "part": 9
  },
  {
    "text": "앵커에 맡겨야 붙어요.",
    "startFrame": 11320,
    "endFrame": 11367,
    "part": 9
  },
  {
    "text": "그래서 사람들 행동은 늘 똑같았습니다.",
    "startFrame": 11367,
    "endFrame": 11450,
    "part": 9
  },
  {
    "text": "사자마자 바로 앵커로 직행.",
    "startFrame": 11450,
    "endFrame": 11509,
    "part": 9
  },
  {
    "text": "사실상 이게 UST를 살 유일한 이유였습니다.",
    "startFrame": 11509,
    "endFrame": 11607,
    "part": 9
  },
  {
    "text": "오르지도 않는 코인을 누가 왜 사겠어요.",
    "startFrame": 11607,
    "endFrame": 11693,
    "part": 9
  },
  {
    "text": "그 19.5% 하나 보고 산 겁니다.",
    "startFrame": 11693,
    "endFrame": 11771,
    "part": 9
  },
  {
    "text": "UST가 잘 팔리니 더 발행되고,",
    "startFrame": 11771,
    "endFrame": 11841,
    "part": 9
  },
  {
    "text": "테라 생태계는 계속 커졌습니다.",
    "startFrame": 11841,
    "endFrame": 11907,
    "part": 9
  },
  {
    "text": "여기서 질문 하나 던지고 갈게요.",
    "startFrame": 11907,
    "endFrame": 11977,
    "part": 9
  },
  {
    "text": "그 이자, 대체 누가 주는 겁니까?",
    "startFrame": 11977,
    "endFrame": 12051,
    "part": 9
  },
  {
    "text": "원래 은행은 이렇게 굴러갑니다.",
    "startFrame": 12051,
    "endFrame": 12118,
    "part": 9
  },
  {
    "text": "누가 돈을 빌려 가서 이자를 냅니다.",
    "startFrame": 12118,
    "endFrame": 12197,
    "part": 9
  },
  {
    "text": "그 돈으로 예금자한테 이자를 주죠.",
    "startFrame": 12197,
    "endFrame": 12272,
    "part": 9
  },
  {
    "text": "이자를 만들어내는 사람은 빌려 간 쪽입니다.",
    "startFrame": 12272,
    "endFrame": 12366,
    "part": 9
  },
  {
    "text": "그런데 앵커는 이 균형이 완전히 깨져 있었습니다.",
    "startFrame": 12366,
    "endFrame": 12469,
    "part": 10
  },
  {
    "text": "맡기는 돈은 산더미인데 빌려 가는 사람은 훨씬 적었어요.",
    "startFrame": 12469,
    "endFrame": 12587,
    "part": 10
  },
  {
    "text": "들어오는 이자보다 나가는 이자가 큰 상태였던 겁니다.",
    "startFrame": 12587,
    "endFrame": 12697,
    "part": 10
  },
  {
    "text": "그럼 모자란 만큼은 어디서 나왔을까요.",
    "startFrame": 12697,
    "endFrame": 12775,
    "part": 10
  },
  {
    "text": "테라를 만든 회사와 재단이 자기 돈으로 채워 넣었습니다.",
    "startFrame": 12775,
    "endFrame": 12893,
    "part": 10
  },
  {
    "text": "이자 지급용 곳간을 따로 만들어두고 모자라면 거기서 꺼내 쓴 거죠.",
    "startFrame": 12893,
    "endFrame": 13034,
    "part": 10
  },
  {
    "text": "바닥이 보이면 다시 부어 넣고요.",
    "startFrame": 13034,
    "endFrame": 13102,
    "part": 10
  },
  {
    "text": "혹시 나라에서 주는 지원금 같은 걸 떠올리셨다면,",
    "startFrame": 13102,
    "endFrame": 13207,
    "part": 10
  },
  {
    "text": "그런 건 아닙니다.",
    "startFrame": 13207,
    "endFrame": 13246,
    "part": 10
  },
  {
    "text": "정부랑은 아무 상관 없어요.",
    "startFrame": 13246,
    "endFrame": 13304,
    "part": 10
  },
  {
    "text": "순수하게 회사 돈이었습니다.",
    "startFrame": 13304,
    "endFrame": 13362,
    "part": 10
  },
  {
    "text": "새로 문 연 카페가 손님 모으려고 커피 공짜로 뿌리는 거 있잖아요.",
    "startFrame": 13362,
    "endFrame": 13504,
    "part": 10
  },
  {
    "text": "그거랑 똑같습니다.",
    "startFrame": 13504,
    "endFrame": 13542,
    "part": 10
  },
  {
    "text": "그 커피값은 손님이 아니라 사장님 주머니에서 나가죠.",
    "startFrame": 13542,
    "endFrame": 13652,
    "part": 10
  },
  {
    "text": "문제는 규모였습니다.",
    "startFrame": 13652,
    "endFrame": 13694,
    "part": 11
  },
  {
    "text": "이 사건이 끝나고 나서,",
    "startFrame": 13694,
    "endFrame": 13742,
    "part": 11
  },
  {
    "text": "미국 경제학자들이 붕괴 과정을 통째로 뜯어본 논문을 냈습니다.",
    "startFrame": 13742,
    "endFrame": 13869,
    "part": 11
  },
  {
    "text": "블록체인에 남은 거래 기록을 하나하나 되짚은 분석인데,",
    "startFrame": 13869,
    "endFrame": 13982,
    "part": 11
  },
  {
    "text": "오늘 나오는 숫자들은 대부분 여기서 가져온 겁니다.",
    "startFrame": 13982,
    "endFrame": 14087,
    "part": 11
  },
  {
    "text": "그 논문에 따르면 2022년 4월 기준,",
    "startFrame": 14087,
    "endFrame": 14169,
    "part": 11
  },
  {
    "text": "앵커가 하루에 메워야 하는 돈이 약 600만 달러였습니다.",
    "startFrame": 14169,
    "endFrame": 14290,
    "part": 11
  },
  {
    "text": "하루에 80억 원.",
    "startFrame": 14290,
    "endFrame": 14328,
    "part": 11
  },
  {
    "text": "한 달이면 2,400억이 그냥 나갑니다.",
    "startFrame": 14328,
    "endFrame": 14411,
    "part": 11
  },
  {
    "text": "이자 주려고요.",
    "startFrame": 14411,
    "endFrame": 14441,
    "part": 11
  },
  {
    "text": "이 숫자만 놓고 사기라고 할 순 없습니다.",
    "startFrame": 14441,
    "endFrame": 14527,
    "part": 11
  },
  {
    "text": "초기 서비스가 마케팅비 쓰는 건 흔한 일이니까요.",
    "startFrame": 14527,
    "endFrame": 14628,
    "part": 11
  },
  {
    "text": "다만 하나는 분명해집니다.",
    "startFrame": 14628,
    "endFrame": 14680,
    "part": 11
  },
  {
    "text": "그 19.5%는 시스템이 스스로 벌어낸 돈이 아니었어요.",
    "startFrame": 14680,
    "endFrame": 14796,
    "part": 11
  },
  {
    "text": "누가 계속 부어줘야 유지되는 숫자였습니다.",
    "startFrame": 14796,
    "endFrame": 14882,
    "part": 11
  },
  {
    "text": "테라 커뮤니티 안에서도 이 이자율을 낮추자는 얘기가 나왔습니다.",
    "startFrame": 14882,
    "endFrame": 15009,
    "part": 12
  },
  {
    "text": "5월 1일부터 좀 더 감당 가능한 수준으로 내리자는 제안이었죠.",
    "startFrame": 15009,
    "endFrame": 15135,
    "part": 12
  },
  {
    "text": "언제까지 이 이자를 줄 수 있느냐.",
    "startFrame": 15135,
    "endFrame": 15204,
    "part": 12
  },
  {
    "text": "이 질문은 이미 나오고 있었습니다.",
    "startFrame": 15204,
    "endFrame": 15274,
    "part": 12
  },
  {
    "text": "사람 심리라는 게 좀 그렇습니다.",
    "startFrame": 15274,
    "endFrame": 15340,
    "part": 12
  },
  {
    "text": "규모가 커지면 안전해 보여요.",
    "startFrame": 15340,
    "endFrame": 15399,
    "part": 12
  },
  {
    "text": "쓰는 사람이 많으면 이미 검증된 거겠거니 싶고요.",
    "startFrame": 15399,
    "endFrame": 15498,
    "part": 12
  },
  {
    "text": "거기다 가격까지 오르면 그 믿음은 더 단단해집니다.",
    "startFrame": 15498,
    "endFrame": 15601,
    "part": 12
  },
  {
    "text": "2022년 4월 5일,",
    "startFrame": 15601,
    "endFrame": 15645,
    "part": 12
  },
  {
    "text": "루나는 약 119.18달러로 고점을 찍습니다.",
    "startFrame": 15645,
    "endFrame": 15736,
    "part": 12
  },
  {
    "text": "1~2년 전만 해도 몇 센트짜리였던 코인이 100달러를 넘었으니 분위기가 어땠을지는 짐작이 가시죠.",
    "startFrame": 15736,
    "endFrame": 15935,
    "part": 12
  },
  {
    "text": "그런데 그 뒤로 암호화폐 시장 전체가 식으면서 루나도 같이 내려옵니다.",
    "startFrame": 15935,
    "endFrame": 16078,
    "part": 12
  },
  {
    "text": "아까 말씀드렸죠.",
    "startFrame": 16078,
    "endFrame": 16111,
    "part": 12
  },
  {
    "text": "UST의 담보는 루나 가격이었습니다.",
    "startFrame": 16111,
    "endFrame": 16185,
    "part": 12
  },
  {
    "text": "루나가 내려간다는 건 안전장치가 얇아진다는 뜻입니다.",
    "startFrame": 16185,
    "endFrame": 16291,
    "part": 12
  },
  {
    "text": "앵커 안쪽에서도 변화가 있었습니다.",
    "startFrame": 16291,
    "endFrame": 16360,
    "part": 13
  },
  {
    "text": "4월 후반, 새로 맡기는 돈은 느려지고 빼가는 돈은 빨라집니다.",
    "startFrame": 16360,
    "endFrame": 16488,
    "part": 13
  },
  {
    "text": "앱을 열어보면 이자율은 여전히 19.5%였습니다.",
    "startFrame": 16488,
    "endFrame": 16587,
    "part": 13
  },
  {
    "text": "겉으로는 달라진 게 하나도 없었어요.",
    "startFrame": 16587,
    "endFrame": 16661,
    "part": 13
  },
  {
    "text": "그 숫자 뒤에서 돈의 방향은 이미 바뀌고 있었는데도요.",
    "startFrame": 16661,
    "endFrame": 16771,
    "part": 13
  },
  {
    "text": "돈은 뉴스보다 먼저 움직입니다.",
    "startFrame": 16771,
    "endFrame": 16832,
    "part": 13
  },
  {
    "text": "여기서 한 번 짚고 가야 할 게 있습니다.",
    "startFrame": 16832,
    "endFrame": 16916,
    "part": 13
  },
  {
    "text": "이 영상은 당시 투자한 사람들을 비웃으려고 만든 게 아닙니다.",
    "startFrame": 16916,
    "endFrame": 17039,
    "part": 13
  },
  {
    "text": "솔직히 말씀드리면,",
    "startFrame": 17039,
    "endFrame": 17076,
    "part": 13
  },
  {
    "text": "지금까지 제가 풀어드린 이 구조를 당시에 다 이해하고 들어간 사람이 몇이나 됐을까요.",
    "startFrame": 17076,
    "endFrame": 17248,
    "part": 13
  },
  {
    "text": "백서를 열면 수식이 나오고, 커뮤니티 글은 죄다 영어입니다.",
    "startFrame": 17248,
    "endFrame": 17369,
    "part": 13
  },
  {
    "text": "게다가 블록체인 하면 다들 떠올리는 게 하나 있죠.",
    "startFrame": 17369,
    "endFrame": 17472,
    "part": 13
  },
  {
    "text": "모든 거래가 공개된다는 것.",
    "startFrame": 17472,
    "endFrame": 17528,
    "part": 13
  },
  {
    "text": "투명하니까 안전할 것 같잖아요.",
    "startFrame": 17528,
    "endFrame": 17591,
    "part": 13
  },
  {
    "text": "근데 공개된 장부하고 이해할 수 있는 장부는 다른 겁니다.",
    "startFrame": 17591,
    "endFrame": 17713,
    "part": 14
  },
  {
    "text": "숫자가 다 보인다고 구조까지 보이는 건 아니에요.",
    "startFrame": 17713,
    "endFrame": 17816,
    "part": 14
  },
  {
    "text": "앞서 말씀드린 그 논문에도 나옵니다.",
    "startFrame": 17816,
    "endFrame": 17894,
    "part": 14
  },
  {
    "text": "자산이 많고 정보가 빠른 쪽이 먼저 빠져나갔고,",
    "startFrame": 17894,
    "endFrame": 17994,
    "part": 14
  },
  {
    "text": "늦게 움직인 쪽이 더 크게 잃었다고요.",
    "startFrame": 17994,
    "endFrame": 18076,
    "part": 14
  },
  {
    "text": "장부가 투명하다고 정보 격차까지 사라지진 않았던 겁니다.",
    "startFrame": 18076,
    "endFrame": 18196,
    "part": 14
  },
  {
    "text": "테라의 약속은 정말 단순했습니다.",
    "startFrame": 18196,
    "endFrame": 18266,
    "part": 14
  },
  {
    "text": "1달러를 지킨다.",
    "startFrame": 18266,
    "endFrame": 18300,
    "part": 14
  },
  {
    "text": "근데 그 약속을 떠받치던 돈의 흐름은 하나도 단순하지 않았어요.",
    "startFrame": 18300,
    "endFrame": 18436,
    "part": 14
  },
  {
    "text": "2022년 5월 7일.",
    "startFrame": 18436,
    "endFrame": 18483,
    "part": 14
  },
  {
    "text": "큰 지갑 두 곳에서 약 3억 7,500만 UST가 한꺼번에 빠져나갑니다.",
    "startFrame": 18483,
    "endFrame": 18638,
    "part": 14
  },
  {
    "text": "저축 앱에 맡겨뒀던 돈을 통째로 인출한 거죠.",
    "startFrame": 18638,
    "endFrame": 18735,
    "part": 14
  },
  {
    "text": "우리 돈으로 5천억 원쯤 됩니다.",
    "startFrame": 18735,
    "endFrame": 18804,
    "part": 14
  },
  {
    "text": "그런데 여기서 진짜 중요한 건 금액이 아닙니다.",
    "startFrame": 18804,
    "endFrame": 18904,
    "part": 14
  },
  {
    "text": "모두가 그 장면을 실시간으로 봤다는 겁니다.",
    "startFrame": 18904,
    "endFrame": 18996,
    "part": 14
  },
  {
    "text": "블록체인은 거래가 공개되니까요.",
    "startFrame": 18996,
    "endFrame": 19062,
    "part": 15
  },
  {
    "text": "누가 언제 얼마를 뺐는지 다 보입니다.",
    "startFrame": 19062,
    "endFrame": 19144,
    "part": 15
  },
  {
    "text": "그래서 큰돈이 한번 빠져나가면, 그걸로 끝나지 않습니다.",
    "startFrame": 19144,
    "endFrame": 19264,
    "part": 15
  },
  {
    "text": "어?",
    "startFrame": 19264,
    "endFrame": 19273,
    "part": 15
  },
  {
    "text": "큰손이 나가네.",
    "startFrame": 19273,
    "endFrame": 19305,
    "part": 15
  },
  {
    "text": "뭘 알고 나가는 거 아냐?",
    "startFrame": 19305,
    "endFrame": 19362,
    "part": 15
  },
  {
    "text": "…나도 일단 빼야 하나?",
    "startFrame": 19362,
    "endFrame": 19416,
    "part": 15
  },
  {
    "text": "한 사람의 출금이 다른 사람한테는 신호가 됩니다.",
    "startFrame": 19416,
    "endFrame": 19520,
    "part": 15
  },
  {
    "text": "그리고 신호는 아주 빠르게 불안으로 번지죠.",
    "startFrame": 19520,
    "endFrame": 19612,
    "part": 15
  },
  {
    "text": "물론 이 인출 때문에 테라가 무너졌다고 할 순 없습니다.",
    "startFrame": 19612,
    "endFrame": 19733,
    "part": 15
  },
  {
    "text": "다만 여기서부터 속도가 붙습니다.",
    "startFrame": 19733,
    "endFrame": 19803,
    "part": 15
  },
  {
    "text": "그것도 아주 빠르게.",
    "startFrame": 19803,
    "endFrame": 19846,
    "part": 15
  },
  {
    "text": "UST가 1달러 밑으로 내려갑니다.",
    "startFrame": 19846,
    "endFrame": 19920,
    "part": 15
  },
  {
    "text": "사실 이것 자체는 흔한 일일 수도 있었어요.",
    "startFrame": 19920,
    "endFrame": 20013,
    "part": 15
  },
  {
    "text": "시장에서는 0.99, 0.995 같은 이탈이 늘 생기니까요.",
    "startFrame": 20013,
    "endFrame": 20141,
    "part": 15
  },
  {
    "text": "근데 이번엔 사람들이 기다려주지 않았습니다.",
    "startFrame": 20141,
    "endFrame": 20232,
    "part": 15
  },
  {
    "text": "불안해진 사람들이 UST를 팔거나 루나로 바꾸기 시작합니다.",
    "startFrame": 20232,
    "endFrame": 20357,
    "part": 16
  },
  {
    "text": "문제는 바꿔 받은 루나를 들고 있을 이유가 없다는 거예요.",
    "startFrame": 20357,
    "endFrame": 20479,
    "part": 16
  },
  {
    "text": "곧바로 팔아버립니다.",
    "startFrame": 20479,
    "endFrame": 20521,
    "part": 16
  },
  {
    "text": "여기서 구조가 뒤집힙니다.",
    "startFrame": 20521,
    "endFrame": 20572,
    "part": 16
  },
  {
    "text": "여기가 이 사건의 심장입니다.",
    "startFrame": 20572,
    "endFrame": 20634,
    "part": 16
  },
  {
    "text": "집중해서 봐주세요.",
    "startFrame": 20634,
    "endFrame": 20672,
    "part": 16
  },
  {
    "text": "앞에서 본 자판기 기억하시죠.",
    "startFrame": 20672,
    "endFrame": 20733,
    "part": 16
  },
  {
    "text": "UST를 넣으면 UST는 태워지고 루나가 새로 찍혀 나옵니다.",
    "startFrame": 20733,
    "endFrame": 20861,
    "part": 16
  },
  {
    "text": "평소엔 아무 문제가 없었습니다.",
    "startFrame": 20861,
    "endFrame": 20926,
    "part": 16
  },
  {
    "text": "넣는 사람이 몇 없었으니까요.",
    "startFrame": 20926,
    "endFrame": 20987,
    "part": 16
  },
  {
    "text": "근데 지금은 모두가 그 앞에 줄을 섰습니다.",
    "startFrame": 20987,
    "endFrame": 21079,
    "part": 16
  },
  {
    "text": "수억 개의 UST가 들어갑니다.",
    "startFrame": 21079,
    "endFrame": 21144,
    "part": 16
  },
  {
    "text": "그만큼의 루나가 찍혀 나옵니다.",
    "startFrame": 21144,
    "endFrame": 21209,
    "part": 16
  },
  {
    "text": "받은 사람들은 그걸 바로 시장에 던집니다.",
    "startFrame": 21209,
    "endFrame": 21297,
    "part": 16
  },
  {
    "text": "공급은 늘고 매도는 쏟아지고, 루나 가격은 주저앉습니다.",
    "startFrame": 21297,
    "endFrame": 21416,
    "part": 16
  },
  {
    "text": "여기까지는 뭐, 그럴 수 있어요.",
    "startFrame": 21416,
    "endFrame": 21485,
    "part": 16
  },
  {
    "text": "진짜 미친 건 그다음입니다.",
    "startFrame": 21485,
    "endFrame": 21542,
    "part": 16
  },
  {
    "text": "자판기 규칙을 다시 봅시다.",
    "startFrame": 21542,
    "endFrame": 21599,
    "part": 16
  },
  {
    "text": "UST 1개를 넣으면 1달러어치 루나를 준다.",
    "startFrame": 21599,
    "endFrame": 21694,
    "part": 16
  },
  {
    "text": "루나가 80달러일 때는 1달러어치가 0.0125개였습니다.",
    "startFrame": 21694,
    "endFrame": 21832,
    "part": 17
  },
  {
    "text": "조금만 찍으면 됐죠.",
    "startFrame": 21832,
    "endFrame": 21879,
    "part": 17
  },
  {
    "text": "루나가 1달러가 되면?",
    "startFrame": 21879,
    "endFrame": 21931,
    "part": 17
  },
  {
    "text": "1개를 줘야 합니다.",
    "startFrame": 21931,
    "endFrame": 21978,
    "part": 17
  },
  {
    "text": "0.01달러가 되면?",
    "startFrame": 21978,
    "endFrame": 22026,
    "part": 17
  },
  {
    "text": "100개를 줘야 해요.",
    "startFrame": 22026,
    "endFrame": 22077,
    "part": 17
  },
  {
    "text": "보이시죠.",
    "startFrame": 22077,
    "endFrame": 22099,
    "part": 17
  },
  {
    "text": "가격이 떨어질수록 자판기는 더 많이 찍어야 합니다.",
    "startFrame": 22099,
    "endFrame": 22217,
    "part": 17
  },
  {
    "text": "많이 찍으니까 더 떨어지고, 더 떨어지니까 또 더 찍고.",
    "startFrame": 22217,
    "endFrame": 22348,
    "part": 17
  },
  {
    "text": "찍고, 떨어지고, 찍고, 떨어지고.",
    "startFrame": 22348,
    "endFrame": 22429,
    "part": 17
  },
  {
    "text": "브레이크를 밟았는데 가속 페달이 같이 밟히는 구조였던 겁니다.",
    "startFrame": 22429,
    "endFrame": 22570,
    "part": 17
  },
  {
    "text": "멈출 방법이 시스템 안에 없었어요.",
    "startFrame": 22570,
    "endFrame": 22649,
    "part": 17
  },
  {
    "text": "이게 그 유명한 죽음의 소용돌이입니다.",
    "startFrame": 22649,
    "endFrame": 22738,
    "part": 17
  },
  {
    "text": "이름이 좀 과하다 싶죠?",
    "startFrame": 22738,
    "endFrame": 22793,
    "part": 17
  },
  {
    "text": "숫자를 보시면 생각이 달라지실 겁니다.",
    "startFrame": 22793,
    "endFrame": 22882,
    "part": 17
  },
  {
    "text": "3일.",
    "startFrame": 22882,
    "endFrame": 22894,
    "part": 17
  },
  {
    "text": "루나 공급량이 10억 개에서 6조 개가 됩니다.",
    "startFrame": 22894,
    "endFrame": 23004,
    "part": 17
  },
  {
    "text": "같은 기간 가격은 80달러 근처에서 거의 0까지 내려갔고요.",
    "startFrame": 23004,
    "endFrame": 23144,
    "part": 17
  },
  {
    "text": "오프닝에서 보신 그 카운터가 바로 이겁니다.",
    "startFrame": 23144,
    "endFrame": 23245,
    "part": 17
  },
  {
    "text": "주식으로 바꿔 보면 이런 겁니다.",
    "startFrame": 23245,
    "endFrame": 23315,
    "part": 18
  },
  {
    "text": "빚 갚겠다고 신주를 계속 찍어냅니다.",
    "startFrame": 23315,
    "endFrame": 23392,
    "part": 18
  },
  {
    "text": "찍을수록 한 주 값어치는 줄어들고,",
    "startFrame": 23392,
    "endFrame": 23465,
    "part": 18
  },
  {
    "text": "줄어드니까 더 많이 찍어야 하고,",
    "startFrame": 23465,
    "endFrame": 23534,
    "part": 18
  },
  {
    "text": "결국 원래 주주 몫은 0에 수렴합니다.",
    "startFrame": 23534,
    "endFrame": 23615,
    "part": 18
  },
  {
    "text": "가격을 지키라고 만든 장치가 가격을 무너뜨리는 엔진이 된 겁니다.",
    "startFrame": 23615,
    "endFrame": 23749,
    "part": 18
  },
  {
    "text": "이틀.",
    "startFrame": 23749,
    "endFrame": 23760,
    "part": 18
  },
  {
    "text": "사람들 생각이 바뀌는 데 걸린 시간입니다.",
    "startFrame": 23760,
    "endFrame": 23849,
    "part": 18
  },
  {
    "text": "그전까지는 UST가 0.98달러여도 다들 느긋했습니다.",
    "startFrame": 23849,
    "endFrame": 23963,
    "part": 18
  },
  {
    "text": "어차피 자판기가 있으니 곧 1달러로 돌아오겠지.",
    "startFrame": 23963,
    "endFrame": 24062,
    "part": 18
  },
  {
    "text": "그 믿음 하나로 버틴 거죠.",
    "startFrame": 24062,
    "endFrame": 24119,
    "part": 18
  },
  {
    "text": "근데 이제 그 믿음이 사라졌습니다.",
    "startFrame": 24119,
    "endFrame": 24192,
    "part": 18
  },
  {
    "text": "루나가 무너지는 걸 두 눈으로 봤으니까요.",
    "startFrame": 24192,
    "endFrame": 24280,
    "part": 18
  },
  {
    "text": "자판기는 멀쩡히 돌아가는데,",
    "startFrame": 24280,
    "endFrame": 24338,
    "part": 18
  },
  {
    "text": "아무도 그 결과를 믿지 않게 된 겁니다.",
    "startFrame": 24338,
    "endFrame": 24422,
    "part": 18
  },
  {
    "text": "그때부터 사람들은 UST를 이렇게 보기 시작합니다.",
    "startFrame": 24422,
    "endFrame": 24532,
    "part": 19
  },
  {
    "text": "이건 1달러짜리가 아니라, 지금 팔리는 값이 진짜 값이다.",
    "startFrame": 24532,
    "endFrame": 24657,
    "part": 19
  },
  {
    "text": "0.68달러면 0.68달러, 0.30달러면 0.30달러.",
    "startFrame": 24657,
    "endFrame": 24779,
    "part": 19
  },
  {
    "text": "1달러라는 기준선 자체가 사라진 겁니다.",
    "startFrame": 24779,
    "endFrame": 24865,
    "part": 19
  },
  {
    "text": "그 순간부터 UST는 더 이상 안정 코인이 아니었습니다.",
    "startFrame": 24865,
    "endFrame": 24986,
    "part": 19
  },
  {
    "text": "테라 측은 유동성을 끌어와서 신뢰를 되돌려보려 했습니다.",
    "startFrame": 24986,
    "endFrame": 25106,
    "part": 19
  },
  {
    "text": "하지만 그때 사람들 머릿속엔 이미 같은 질문 하나만 남아 있었어요.",
    "startFrame": 25106,
    "endFrame": 25250,
    "part": 19
  },
  {
    "text": "누가 마지막에 나가게 되는가.",
    "startFrame": 25250,
    "endFrame": 25312,
    "part": 19
  },
  {
    "text": "이 질문이 나오기 시작하면 사실 결론은 난 겁니다.",
    "startFrame": 25312,
    "endFrame": 25421,
    "part": 19
  },
  {
    "text": "모두가 동시에 나갈 수 있는 출구란 건 어디에도 없으니까요.",
    "startFrame": 25421,
    "endFrame": 25549,
    "part": 19
  },
  {
    "text": "다시 말씀드리지만 이 사건은 누가 작정하고 벌인 일이 아닙니다.",
    "startFrame": 25549,
    "endFrame": 25692,
    "part": 20
  },
  {
    "text": "감당 못 할 수익률, 루나 하나에만 기댄 담보 구조,",
    "startFrame": 25692,
    "endFrame": 25811,
    "part": 20
  },
  {
    "text": "식어가던 시장, 그리고 한꺼번에 몰린 출금.",
    "startFrame": 25811,
    "endFrame": 25909,
    "part": 20
  },
  {
    "text": "이 네 가지가 같은 방향으로 겹쳤습니다.",
    "startFrame": 25909,
    "endFrame": 25999,
    "part": 20
  },
  {
    "text": "그 끝에서 UST는 1달러를 잃었습니다.",
    "startFrame": 25999,
    "endFrame": 26090,
    "part": 20
  },
  {
    "text": "루나는 충격을 막아주는 쪽이 아니라,",
    "startFrame": 26090,
    "endFrame": 26172,
    "part": 20
  },
  {
    "text": "손실이 전부 쏟아져 들어오는 쪽이 됐고요.",
    "startFrame": 26172,
    "endFrame": 26266,
    "part": 20
  },
  {
    "text": "지금까지 우리가 본 건 구조였습니다.",
    "startFrame": 26266,
    "endFrame": 26349,
    "part": 20
  },
  {
    "text": "자판기, 저울, 톱니바퀴.",
    "startFrame": 26349,
    "endFrame": 26406,
    "part": 20
  },
  {
    "text": "그런데 그 톱니 사이에 사람이 있었습니다.",
    "startFrame": 26406,
    "endFrame": 26501,
    "part": 20
  },
  {
    "text": "한번 이렇게 상상해 보시죠.",
    "startFrame": 26501,
    "endFrame": 26561,
    "part": 20
  },
  {
    "text": "코인은 잘 모릅니다.",
    "startFrame": 26561,
    "endFrame": 26607,
    "part": 20
  },
  {
    "text": "비트코인은 무섭다고 들었어요.",
    "startFrame": 26607,
    "endFrame": 26675,
    "part": 20
  },
  {
    "text": "하루에 몇십 퍼센트씩 빠진다니까요.",
    "startFrame": 26675,
    "endFrame": 26755,
    "part": 20
  },
  {
    "text": "그런데 누가 이런 걸 알려줍니다.",
    "startFrame": 26755,
    "endFrame": 26830,
    "part": 20
  },
  {
    "text": "\"이건 가격이 안 움직여.",
    "startFrame": 26830,
    "endFrame": 26889,
    "part": 20
  },
  {
    "text": "1달러에 딱 고정돼 있어.",
    "startFrame": 26889,
    "endFrame": 26948,
    "part": 20
  },
  {
    "text": "근데 이자를 20% 줘.\"",
    "startFrame": 26948,
    "endFrame": 27007,
    "part": 20
  },
  {
    "text": "위험한 코인이 아니라 안전한 코인이라고 했습니다.",
    "startFrame": 27007,
    "endFrame": 27124,
    "part": 21
  },
  {
    "text": "게다가 매일 잔액이 아주 조금씩 늘어나는 게 보입니다.",
    "startFrame": 27124,
    "endFrame": 27255,
    "part": 21
  },
  {
    "text": "그래서 넣습니다.",
    "startFrame": 27255,
    "endFrame": 27296,
    "part": 21
  },
  {
    "text": "처음엔 조금.",
    "startFrame": 27296,
    "endFrame": 27327,
    "part": 21
  },
  {
    "text": "잘 되니까 더 많이.",
    "startFrame": 27327,
    "endFrame": 27377,
    "part": 21
  },
  {
    "text": "전세금을 넣은 사람도 있었고,",
    "startFrame": 27377,
    "endFrame": 27450,
    "part": 21
  },
  {
    "text": "퇴직금을 넣은 사람도 있었습니다.",
    "startFrame": 27450,
    "endFrame": 27532,
    "part": 21
  },
  {
    "text": "그리고 5월의 어느 밤, 숫자가 0.98이 됩니다.",
    "startFrame": 27532,
    "endFrame": 27651,
    "part": 21
  },
  {
    "text": "자, 여기서 어떻게 하시겠어요.",
    "startFrame": 27651,
    "endFrame": 27724,
    "part": 21
  },
  {
    "text": "지금 팔면 2%를 손해 봅니다.",
    "startFrame": 27724,
    "endFrame": 27801,
    "part": 21
  },
  {
    "text": "아깝죠.",
    "startFrame": 27801,
    "endFrame": 27819,
    "part": 21
  },
  {
    "text": "게다가 여태 잘 돌아왔잖아요.",
    "startFrame": 27819,
    "endFrame": 27892,
    "part": 21
  },
  {
    "text": "사람들은 기다렸습니다.",
    "startFrame": 27892,
    "endFrame": 27946,
    "part": 21
  },
  {
    "text": "곧 1달러로 돌아올 거니까.",
    "startFrame": 27946,
    "endFrame": 28014,
    "part": 21
  },
  {
    "text": "기다린 사람들의 돈은 돌아오지 않았습니다.",
    "startFrame": 28014,
    "endFrame": 28112,
    "part": 21
  },
  {
    "text": "이게 이 사건에서 제일 잔인한 부분입니다.",
    "startFrame": 28112,
    "endFrame": 28213,
    "part": 21
  },
  {
    "text": "겁 없이 도박한 사람들이 당한 게 아니에요.",
    "startFrame": 28213,
    "endFrame": 28317,
    "part": 21
  },
  {
    "text": "위험을 피하고 싶어서 안전해 보이는 쪽을 고른 사람들이 당했습니다.",
    "startFrame": 28317,
    "endFrame": 28479,
    "part": 21
  },
  {
    "text": "50조라는 숫자는 그냥 숫자가 아닙니다.",
    "startFrame": 28479,
    "endFrame": 28575,
    "part": 21
  },
  {
    "text": "누군가의 전세금이고, 누군가의 몇 년치 월급이었습니다.",
    "startFrame": 28575,
    "endFrame": 28705,
    "part": 21
  },
  {
    "text": "그 뒤 책임 문제는 법정으로 넘어갔습니다.",
    "startFrame": 28705,
    "endFrame": 28762,
    "part": 22
  },
  {
    "text": "배심원단은 Terraform과 권도형이 투자자를 속였다고 평결했습니다.",
    "startFrame": 28762,
    "endFrame": 28862,
    "part": 22
  },
  {
    "text": "그리고 45억 달러가 넘는 돈을 내기로 합의가 이뤄졌고요.",
    "startFrame": 28862,
    "endFrame": 28943,
    "part": 22
  },
  {
    "text": "권도형은 2025년 미국 법정에서 사기 관련 혐의에 유죄를 인정했고,",
    "startFrame": 28943,
    "endFrame": 29040,
    "part": 22
  },
  {
    "text": "15년형을 선고받았습니다.",
    "startFrame": 29040,
    "endFrame": 29076,
    "part": 22
  },
  {
    "text": "그런데 법원이 밝혀준 건 누가 책임을 지느냐까지입니다.",
    "startFrame": 29076,
    "endFrame": 29153,
    "part": 22
  },
  {
    "text": "왜 이런 구조가 만들어졌고 어쩌다 이렇게 무너졌는지,",
    "startFrame": 29153,
    "endFrame": 29227,
    "part": 22
  },
  {
    "text": "그건 판결문에 안 나옵니다.",
    "startFrame": 29227,
    "endFrame": 29266,
    "part": 22
  },
  {
    "text": "그래서 저는 오늘 그 이야기를 하고 싶었습니다.",
    "startFrame": 29266,
    "endFrame": 29332,
    "part": 22
  },
  {
    "text": "그럼 이 사건에서 우리가 배울 건 뭘까요.",
    "startFrame": 29332,
    "endFrame": 29389,
    "part": 22
  },
  {
    "text": "첫째, 이름에 '안정'이 붙었다고 금고가 있는 건 아닙니다.",
    "startFrame": 29389,
    "endFrame": 29474,
    "part": 22
  },
  {
    "text": "스테이블코인이라고 다 같은 스테이블코인이 아니에요.",
    "startFrame": 29474,
    "endFrame": 29545,
    "part": 22
  },
  {
    "text": "이름 말고, 뭘로 그 안정을 유지하는지를 봐야 합니다.",
    "startFrame": 29545,
    "endFrame": 29622,
    "part": 22
  },
  {
    "text": "달러인지, 국채인지, 아니면 다른 코인 가격인지.",
    "startFrame": 29622,
    "endFrame": 29690,
    "part": 22
  },
  {
    "text": "둘째, 수익률보다 그 수익이 어디서 나오는지가 먼저입니다.",
    "startFrame": 29690,
    "endFrame": 29813,
    "part": 23
  },
  {
    "text": "연 19.5%.",
    "startFrame": 29813,
    "endFrame": 29843,
    "part": 23
  },
  {
    "text": "이건 그냥 숫자에 불과합니다.",
    "startFrame": 29843,
    "endFrame": 29904,
    "part": 23
  },
  {
    "text": "진짜 봐야 할 건 그 뒤예요.",
    "startFrame": 29904,
    "endFrame": 29965,
    "part": 23
  },
  {
    "text": "이 이자를 누가 벌어서, 누구 돈으로, 언제까지 주는가.",
    "startFrame": 29965,
    "endFrame": 30084,
    "part": 23
  },
  {
    "text": "여기에 답이 없다면,",
    "startFrame": 30084,
    "endFrame": 30126,
    "part": 23
  },
  {
    "text": "그 돈은 결국 참여자 중 누군가의 주머니에서 나오고 있는 겁니다.",
    "startFrame": 30126,
    "endFrame": 30263,
    "part": 23
  },
  {
    "text": "셋째, 투명하다고 쉬운 건 아닙니다.",
    "startFrame": 30263,
    "endFrame": 30340,
    "part": 23
  },
  {
    "text": "테라의 장부는 처음부터 끝까지 다 공개돼 있었습니다.",
    "startFrame": 30340,
    "endFrame": 30451,
    "part": 23
  },
  {
    "text": "그런데도 대부분은 늦게 알았어요.",
    "startFrame": 30451,
    "endFrame": 30520,
    "part": 23
  },
  {
    "text": "기억해 두세요.",
    "startFrame": 30520,
    "endFrame": 30551,
    "part": 23
  },
  {
    "text": "복잡함은 어둠 속에만 숨는 게 아니라,",
    "startFrame": 30551,
    "endFrame": 30631,
    "part": 23
  },
  {
    "text": "밝은 곳에도 숨는다는 것을요.",
    "startFrame": 30631,
    "endFrame": 30693,
    "part": 23
  },
  {
    "text": "그런데 여기서 끝내면 안 될 것 같습니다.",
    "startFrame": 30693,
    "endFrame": 30779,
    "part": 23
  },
  {
    "text": "왜냐하면 이게 다 끝난 옛날얘기가 아니거든요.",
    "startFrame": 30779,
    "endFrame": 30872,
    "part": 23
  },
  {
    "text": "이 사건 이후에 스테이블코인 시장이 사라졌을까요.",
    "startFrame": 30872,
    "endFrame": 30972,
    "part": 24
  },
  {
    "text": "반대입니다.",
    "startFrame": 30972,
    "endFrame": 30994,
    "part": 24
  },
  {
    "text": "2026년 5월 기준 전체 스테이블코인 시가총액은 3,217억 달러로 사상 최고치를 찍었습니다.",
    "startFrame": 30994,
    "endFrame": 31189,
    "part": 24
  },
  {
    "text": "2026년 1월 한 달 이체량은 10조 달러를 넘었고요.",
    "startFrame": 31189,
    "endFrame": 31303,
    "part": 24
  },
  {
    "text": "테라가 무너지기 직전인 2022년 4월 이후 가장 큰 규모입니다.",
    "startFrame": 31303,
    "endFrame": 31435,
    "part": 24
  },
  {
    "text": "지금 스테이블코인은 거래소 안에만 있지 않습니다.",
    "startFrame": 31435,
    "endFrame": 31534,
    "part": 24
  },
  {
    "text": "결제에 쓰이고, 송금에 쓰이고, 기관들이 정산에 씁니다.",
    "startFrame": 31534,
    "endFrame": 31648,
    "part": 24
  },
  {
    "text": "그러니까 이건 코인 하는 사람들만의 얘기가 아니게 된 겁니다.",
    "startFrame": 31648,
    "endFrame": 31772,
    "part": 24
  },
  {
    "text": "그리고 그 코인들은 겉으로 보면 다 똑같이 생겼습니다.",
    "startFrame": 31772,
    "endFrame": 31883,
    "part": 24
  },
  {
    "text": "전부 1달러라고 적혀 있어요.",
    "startFrame": 31883,
    "endFrame": 31942,
    "part": 24
  },
  {
    "text": "뭐가 뒤에 있는지는, 열어봐야 압니다.",
    "startFrame": 31942,
    "endFrame": 32019,
    "part": 24
  },
  {
    "text": "이 영상은 특정 자산을 사라거나 팔라는 얘기가 아닙니다.",
    "startFrame": 32019,
    "endFrame": 32132,
    "part": 24
  },
  {
    "text": "우리는 그저 돈이 어떤 약속을 믿고 움직였는지를 따라가 봤을 뿐입니다.",
    "startFrame": 32132,
    "endFrame": 32274,
    "part": 24
  },
  {
    "text": "이 사건이 남긴 건 결국 이 한 문장입니다.",
    "startFrame": 32274,
    "endFrame": 32367,
    "part": 25
  },
  {
    "text": "시장에서 가장 먼저 무너지는 건 가격이 아닙니다.",
    "startFrame": 32367,
    "endFrame": 32476,
    "part": 25
  },
  {
    "text": "믿음입니다.",
    "startFrame": 32476,
    "endFrame": 32500,
    "part": 25
  },
  {
    "text": "가격은 그다음이고요.",
    "startFrame": 32500,
    "endFrame": 32544,
    "part": 25
  },
  {
    "text": "마지막으로 하나 여쭤보고 싶습니다.",
    "startFrame": 32544,
    "endFrame": 32618,
    "part": 25
  },
  {
    "text": "여러분이라면 그 밤에 어떻게 하셨을 것 같으세요.",
    "startFrame": 32618,
    "endFrame": 32727,
    "part": 25
  },
  {
    "text": "0.98달러.",
    "startFrame": 32727,
    "endFrame": 32756,
    "part": 25
  },
  {
    "text": "지금 팔면 2% 손해.",
    "startFrame": 32756,
    "endFrame": 32804,
    "part": 25
  },
  {
    "text": "기다리면 돌아올지도 모르는 상황.",
    "startFrame": 32804,
    "endFrame": 32877,
    "part": 25
  },
  {
    "text": "팔았을까요, 기다렸을까요.",
    "startFrame": 32877,
    "endFrame": 32934,
    "part": 25
  },
  {
    "text": "댓글에 적어주시면 다음 영상 만들 때 참고하겠습니다.",
    "startFrame": 32934,
    "endFrame": 33048,
    "part": 25
  },
  {
    "text": "사실 이게 이 채널이 계속 다루게 될 질문이거든요.",
    "startFrame": 33048,
    "endFrame": 33158,
    "part": 25
  },
  {
    "text": "다음 화에서는 은행 하나가 단 이틀 만에 사라진 사건을 다룹니다.",
    "startFrame": 33158,
    "endFrame": 33301,
    "part": 25
  },
  {
    "text": "이번엔 코인이 아닙니다.",
    "startFrame": 33301,
    "endFrame": 33352,
    "part": 25
  },
  {
    "text": "미국에서 열여섯 번째로 큰, 진짜 은행이었습니다.",
    "startFrame": 33352,
    "endFrame": 33459,
    "part": 25
  },
  {
    "text": "그리고 그 은행을 무너뜨린 건 예금자들의 문자메시지였습니다.",
    "startFrame": 33459,
    "endFrame": 33590,
    "part": 25
  },
  {
    "text": "돈이 움직인 사건을 계속 추적합니다.",
    "startFrame": 33590,
    "endFrame": 33669,
    "part": 25
  },
  {
    "text": "구독해 두시면 다음 궤적도 놓치지 않으실 겁니다.",
    "startFrame": 33669,
    "endFrame": 33776,
    "part": 25
  },
  {
    "text": "그럼 다음 사건에서 뵙겠습니다.",
    "startFrame": 33776,
    "endFrame": 33841,
    "part": 25
  }
];
